---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db
  labels:
    app: todo-db
spec:
  serviceName: "todo-db"
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: todo-db
          image: docker.io/postgres:17.0-alpine3.20
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: todo-db-env
            - secretRef:
                name: todo-db-secrets
          volumeMounts:
            - name: todo
              mountPath: /var/lib/postgres
  volumeClaimTemplates:
    - metadata:
        name: todo
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
