// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Todo.Api.Account.Context;

#nullable disable

namespace Todo.Api.Migrations
{
    [DbContext(typeof(AccountContext))]
    [Migration("20241202173642_Update_Desing_Version")]
    partial class Update_Desing_Version
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Todo.Api.Account.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Key")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("RegisterDate")
                        .HasColumnType("date")
                        .HasColumnName("register_date");

                    b.HasKey("Key");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Todo.Api.Account.Models.UserEntity", b =>
                {
                    b.OwnsOne("Todo.Api.Account.Models.DetailAccount", "Detail", b1 =>
                        {
                            b1.Property<Guid>("UserEntityKey")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(30)
                                .HasColumnType("varchar")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .HasMaxLength(30)
                                .HasColumnType("varchar")
                                .HasColumnName("last_name");

                            b1.HasKey("UserEntityKey");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityKey");
                        });

                    b.OwnsOne("Todo.Api.Account.Models.SecurityAccount", "Security", b1 =>
                        {
                            b1.Property<Guid>("UserEntityKey")
                                .HasColumnType("uuid");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("password");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar")
                                .HasColumnName("user_name");

                            b1.HasKey("UserEntityKey");

                            b1.HasIndex("UserName")
                                .IsUnique();

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityKey");
                        });

                    b.Navigation("Detail");

                    b.Navigation("Security")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
