global using Riok.Mapperly;
global using Microsoft.EntityFrameworkCore;
global using Todo.Api.Common.Models;
global using Todo.Api.Common.Context.Config;
global using Todo.Api; 
global using Todo.Api.Common.Handlers;
global using Ardalis.Result;
global using Todo.Shared.Models.Request;
global using Todo.Shared.Models.Response;